# Create here the Drupal site you would like
version: '2'
services:
  drupal:
    build: .
    # Choose your URL and hostname for this Docker Container
    # NEEDS to end with '.docker.amazee.io' !
    # DO NOT remove the '&hostname'
    hostname: &hostname docs.amazee.io.docker.amazee.io

    environment:
      AMAZEEIO: AMAZEEIO
      AMAZEEIO_URL: *hostname
      AMAZEEIO_HTTP_PORT: 8080
      WEBROOT: _book
      VIRTUAL_HOST: *hostname
    container_name: *hostname
    volumes:
      - ./_book:/app
    network_mode: bridge
